### ISSUE TITLE
Use-case template

### ISSUE THREAD

**Issue by eocarragain** [ResearchObject/ro-lite#6]
As discussed in the first call, we need a template to capture use-cases

It may be enough to capture these as user stories, i.e.
`As a < type of user >, I want < some goal > so that < some reason >.`

However, we might also want to use a fuller use-case template. See, for example, the Use Case template used by the w3c Data Exchange Working Group: https://www.w3.org/2017/dxwg/wiki/Use_Case_Working_Space#.2F.2FUse_Case_template

cc @stain @ptsefton

**Comment by stain** [comment]
I think the basic template you suggest is good and quite well known, and we can allow diverging from it where needed, but should not need initially to detail them as much as the W3C example (which looks pretty good, don't get me wrong!).

Here are some recent ones we started with CWL which are more free-text Alice/Bob style:  https://docs.google.com/document/d/1I8HRltcQKYVlvI03ARL_A3IahdIg85GJ0gXTUW-S0TU/edit

Do we collect the use cases here in this issue, or in a Google Doc? I think one github issue per use case might be a bit overkill (unless we do it by the W3C style).

**Comment by eocarragain** [comment]
Agree - let's keep the simply user story as a basis. Specific or more complex use cases can optionally supply more detail (using the w3c template as a basis?), but the simple user story will be sufficient in most cases.

I'd be in favour of using github for this, so each user story can be managed/tagged/discussed separately. Examples of this:

- The Oxford Common Filesystem Layout (OCFL) spec have a separate repo just for use-cases and they use github labels to manage, e.g. "Confirmed: In-scope"/"Confirm: Supported"/"Confirmed: Out-of-scope". See https://github.com/OCFL/Use-Cases/issues?q=is%3Aissue+is%3Aclosed

- The Freya project captured a lot of user stories as issues in their main github repo. Again they used github labels to distinguish user stories from other types of issues: https://github.com/datacite/freya/issues?q=is%3Aissue+label%3A%22user+story%22+is%3Aclosed

Alternatively, Google Doc plus inline comments would also work.

**Comment by stain** [comment]
OK, you have convinced me, +1 to manage the user stories as GitHub issues - this avoids Google Docification which I have seen many times, where the only outcome is a 40 page document. 

I've added a new issue template (feel free to modify!)
https://github.com/ResearchObject/ro-lite/blob/master/.github/ISSUE_TEMPLATE/use-case.md

The template should then come up if you select [New Issue](https://github.com/ResearchObject/ro-lite/issues/new/choose)
